### PR TITLE
Codon support. 74 times speedup compared to Python

### PR DESCRIPTION
**Pull request by dmahurin**
This set of changes adds ability to compile llama2.py with Codon.

The result is a 74 X speedup!

As Codon currently has no 'struct', this required implementing trivial struct functions used here.  But only Codon would see that. The other changes are clean python changes for Codon compatibility.
 
---

% python3 llama2.py stories15M.bin 0 8 ' Linus'
Linus was walking in the park.
achieved tok/s: 0.9232392508572935

% mypyc llama2.py
% python3 -c 'import llama2' stories15M.bin 0 8 ' Linus'
Linus was walking in the park.
achieved tok/s: 0.9944594402614008

(1.1x)

% codon run llama2.py stories15M.bin 0 8 ' Linus'
Linus was walking in the park.
achieved tok/s: 10.4948

(11x)

% codon run --release llama2.py stories15M.bin 0 8 ' Linus'
Linus was walking in the park.
achieved tok/s: 68.6275

(74x)

### CODE REVIEW

**Comment by dmahurin** [comment]
All the changes to support Codon are now fine for python as well.

Latest changes implement a trivial struct.codon, inspired by a comment by  @arshajii in codon

https://github.com/exaloop/codon/issues/490

**Comment by tairov** [comment]
Hi @dmahurin , thanks for PR. Looks cool.
I didn't get how to run this, though :)
Could you please add more details how to achieve the speedup ?

**Comment by tairov** [comment]
Also, does the `codon` related changes 100% compatible with standard python? I see you've added struct & types

**Comment by dmahurin** [comment]
Hi @tairov.

Install codon with the instructions at:

https://github.com/exaloop/codon

```
/bin/bash -c "$(curl -fsSL https://exaloop.io/install.sh)"
```

Then simply run it  with 'codon run --release', with the same args you pass to python.

```
codon run --release llama2.py stories15M.bin 0 8 ' Linus'
```

And yes, the modified code still works on python3.

I worked around missing struct on codon, by implementing the functions needed in codon.  But python would never see that.

```
python3 llama2.py stories15M.bin 0 8 ' Linus'
```

**Comment by dmahurin** [comment]
I just force pushed and changed list[float] to List[float].  for pypy3.

And noticed that pypy3 is much faster than python3 for llama2.py, though codon is faster.

**Comment by tairov** [comment]
Look good! Thank you !

**Pull request merged**
